apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      serviceAccountName: nextflow
      containers:
        - name: globflow
          image: {{ .Values.baseImage }}:{{ .Values.dockerTag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ['sh', '-c', "nextflow run https://gitlab.ebi.ac.uk/gdp-public/globflow.git -params-file /opt/nxf/params.yml -c /opt/nxf/nxf.config --decrypt"]
          env:
            - name: NXF_SCM_FILE
              value: /opt/nxf/scm
          resources:
            requests:
              cpu: "1"
              memory: 2G
              ephemeral-storage: 10G
          volumeMounts:
            - name: transfer-config
              mountPath: /opt/nxf
            - name: globflow-secrets
              mountPath: /opt/globflow/
              readOnly: true
      volumes:
      - name: transfer-config
        configMap:
          name: {{ .Release.Name }}-transfer-config
          items:
          - key: nxf.config
            path: nxf.config
          - key: scm
            path: scm
          - key: params.yml
            path: params.yml
          - key: input.json
            path: input.json
          - key: key.json
            path: key.json
      - name: globflow-secrets
        secret:
          secretName: {{ .Release.Name }}-transfer-secrets
      restartPolicy: Never